In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
pd.set_option('display.max_columns', None) 
pd.set_option('display.max_rows', None)  
pd.set_option('display.max_colwidth', -1)

In [2]:
df = pd.read_csv('train.csv')

# LET US FIRST START BY EXPLORING THE DATA

In [3]:
df.head()

,label,id,visitTime,purchaseTime,hour,C1,C2,C3,C4,C5,C6,C7,C8,N1,C9,N2,N3,N4,N5,N6,N7,N8,N9,N10,C10,C11,C12
0,-1,37,19274330,-1,0,2569487005,1830830742,4228834423,652481754,2967512603,3624739744,2303407174,2206061889,0,4287642944,0,0,0,0,0,0,0,0,0,419316267,3617851689,4220791646
1,-1,55,19274334,-1,0,3191875643,403381353,1238330876,652481754,2967512603,179712055,2303407174,157533148,1,3272771221,0,1,0,0,0,0,1,0,0,1968545380,3831440054,1213938795
2,-1,114,19274353,-1,0,2634604934,403381353,1928325921,652481754,2967512603,1607619193,2303407174,3588031319,0,3329757940,0,0,0,0,0,0,0,0,0,1405802835,2379633508,1284343215
3,-1,128,19274358,-1,0,2569487005,403381353,296915027,652481754,2967512603,10212495,2303407174,3588031319,0,3427046189,0,0,0,0,0,0,0,0,0,2299319102,3617851689,4220791646
4,-1,164,19274367,-1,0,2569487005,403381353,681762206,652481754,2967512603,580883881,2303407174,157533148,0,2088887026,0,0,0,0,0,0,0,0,0,1306075469,3617851689,4220791646

In [4]:
df.describe()

,label,id,visitTime,purchaseTime,hour,C1,C2,C3,C4,C5,C6,C7,C8,N1,C9,N2,N3,N4,N5,N6,N7,N8,N9,N10,C10,C11,C12
count,31428.000000,31428.000000,3.142800e+04,3.142800e+04,31428.000000,3.142800e+04,3.142800e+04,3.142800e+04,3.142800e+04,3.142800e+04,3.142800e+04,3.142800e+04,3.142800e+04,31428.000000,3.142800e+04,31428.000000,31428.000000,31428.000000,31428.000000,31428.000000,31428.000000,31428.000000,31428.000000,31428.000000,3.142800e+04,3.142800e+04,3.142800e+04
mean,-0.996373,321870.448835,1.931855e+07,3.504330e+04,11.799701,2.264373e+09,1.331820e+09,2.255368e+09,1.018468e+09,2.741699e+09,1.864977e+09,2.164069e+09,1.961886e+09,0.510882,2.260150e+09,0.419594,0.169849,0.134307,0.002386,0.027269,0.002164,0.415680,0.042319,0.057560,2.218926e+09,2.939366e+09,2.158890e+09
std,0.085098,184665.780120,1.690395e+04,8.221503e+05,4.695434,1.077516e+09,7.900907e+08,1.125852e+09,7.260969e+08,3.771211e+08,1.359663e+09,4.764277e+08,1.216958e+09,1.157846,1.373591e+09,1.681422,1.286043,1.258795,0.156001,0.562668,0.079745,3.184785,1.008314,1.158253,1.235285e+09,1.020598e+09,1.416777e+09
min,-1.000000,37.000000,1.927433e+07,-1.000000e+00,0.000000,7.942600e+04,4.033814e+08,5.538985e+06,3.063949e+08,2.116767e+09,1.021250e+07,5.493426e+08,1.575331e+08,0.000000,1.469265e+07,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.626600e+04,4.393702e+07,2.456084e+08
25%,-1.000000,162636.500000,1.930609e+07,-1.000000e+00,8.000000,1.464958e+09,4.033814e+08,1.408383e+09,6.524818e+08,2.116767e+09,5.717657e+08,2.303407e+09,4.348284e+08,0.000000,1.097314e+09,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.140301e+09,2.379634e+09,1.213939e+09
50%,-1.000000,322691.500000,1.931761e+07,-1.000000e+00,12.000000,2.569487e+09,1.235983e+09,2.243934e+09,6.524818e+08,2.967513e+09,1.955108e+09,2.303407e+09,2.206062e+09,0.000000,2.226683e+09,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.274128e+09,3.617852e+09,1.284343e+09
75%,-1.000000,481852.000000,1.933113e+07,-1.000000e+00,15.000000,2.834768e+09,2.018710e+09,3.326547e+09,6.524818e+08,2.967513e+09,2.712499e+09,2.303407e+09,2.374955e+09,0.000000,3.329758e+09,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.376114e+09,3.831440e+09,4.220792e+09
max,1.000000,638505.000000,1.936054e+07,1.935732e+07,23.000000,4.294924e+09,2.541204e+09,4.292704e+09,2.308171e+09,3.955179e+09,4.288421e+09,3.649212e+09,4.143495e+09,5.000000,4.287643e+09,15.000000,20.000000,20.000000,20.000000,20.000000,10.000000,97.000000,85.000000,86.000000,4.294964e+09,3.831440e+09,4.220792e+09

In [5]:
df.isnull().sum()

label           0
id              0
visitTime       0
purchaseTime    0
hour            0
C1              0
C2              0
C3              0
C4              0
C5              0
C6              0
C7              0
C8              0
N1              0
C9              0
N2              0
N3              0
N4              0
N5              0
N6              0
N7              0
N8              0
N9              0
N10             0
C10             0
C11             0
C12             0
dtype: int64

As we can see there are no missing values in this dataset, we are good to go.

In [6]:
df.corr()

,label,id,visitTime,purchaseTime,hour,C1,C2,C3,C4,C5,C6,C7,C8,N1,C9,N2,N3,N4,N5,N6,N7,N8,N9,N10,C10,C11,C12
label,1.000000,0.006510,0.005782,1.000000,0.005959,-0.002729,0.003435,-0.000707,-0.005857,0.008654,0.017486,-0.036506,0.004194,0.041259,0.029978,0.008043,0.117648,0.203383,0.071254,0.230524,0.092622,0.232069,0.514412,0.470503,-0.005066,-0.001280,-0.016744
id,0.006510,1.000000,0.985723,0.006543,0.984233,0.011131,-0.031077,-0.014507,0.048138,-0.044974,0.027836,0.009746,0.125961,0.017362,0.112332,-0.018011,0.035546,0.026743,0.006860,0.012628,-0.001135,0.035148,0.013390,0.012329,-0.000430,0.053341,0.070517
visitTime,0.005782,0.985723,1.000000,0.005815,0.998092,0.011742,-0.021600,-0.011627,0.051565,-0.040371,0.059132,0.008802,0.119564,0.012089,0.082722,-0.021907,0.036165,0.026420,0.006853,0.014143,-0.000400,0.036550,0.013527,0.012626,-0.000176,0.051994,0.072373
purchaseTime,1.000000,0.006543,0.005815,1.000000,0.005992,-0.002730,0.003442,-0.000712,-0.005860,0.008663,0.017483,-0.036515,0.004197,0.041267,0.029986,0.008046,0.117632,0.203410,0.071303,0.230528,0.092630,0.232101,0.514525,0.470614,-0.005069,-0.001278,-0.016742
hour,0.005959,0.984233,0.998092,0.005992,1.000000,0.011623,-0.021613,-0.012099,0.051268,-0.039976,0.058947,0.008625,0.119237,0.014503,0.083878,-0.020094,0.036497,0.027168,0.006560,0.014412,-0.000202,0.037086,0.013552,0.012575,-0.000184,0.052295,0.071955
C1,-0.002729,0.011131,0.011742,-0.002730,0.011623,1.000000,0.024736,0.021227,0.042015,0.049402,0.013999,0.031409,-0.007672,-0.051824,0.007018,-0.024245,-0.015229,-0.013335,-0.005202,0.010162,0.005695,-0.013904,-0.006939,-0.011425,0.000293,0.072482,0.148559
C2,0.003435,-0.031077,-0.021600,0.003442,-0.021613,0.024736,1.000000,-0.033626,0.522098,0.188290,-0.024301,0.046606,-0.295987,0.009429,-0.049385,0.038045,-0.024341,0.012293,-0.003979,0.021354,0.005619,0.004571,0.007887,0.010729,-0.055098,0.111602,0.133126
C3,-0.000707,-0.014507,-0.011627,-0.000712,-0.012099,0.021227,-0.033626,1.000000,-0.051367,0.035305,0.011187,-0.000490,0.020281,-0.002296,-0.072116,-0.034679,-0.002251,-0.002444,0.008495,0.002335,-0.003647,0.002815,0.003306,0.004317,0.000864,0.021532,0.074496
C4,-0.005857,0.048138,0.051565,-0.005860,0.051268,0.042015,0.522098,-0.051367,1.000000,0.301824,0.018999,0.036268,-0.098485,0.006588,-0.025080,-0.019544,-0.039773,-0.010637,-0.005169,0.003998,-0.006557,-0.018941,-0.008732,-0.006200,-0.022361,0.128080,0.211202
C5,0.008654,-0.044974,-0.040371,0.008663,-0.039976,0.049402,0.188290,0.035305,0.301824,1.000000,0.125719,0.008757,-0.201160,0.264212,0.117501,0.149258,-0.060791,0.040794,-0.020289,0.024300,0.005445,0.007496,0.015806,0.018107,-0.093148,0.109476,0.265741
C6,0.017486,0.027836,0.059132,0.017483,0.058947,0.013999,-0.024301,0.011187,0.018999,0.125719,1.000000,-0.002959,-0.009156,-0.037446,-0.236198,-0.046455,0.085084,0.018428,0.020634,0.019519,-0.000492,0.069547,0.024832,0.029970,0.016071,-0.008306,0.039842
C7,-0.036506,0.009746,0.008802,-0.036515,0.008625,0.031409,0.046606,-0.000490,0.036268,0.008757,-0.002959,1.000000,-0.062604,-0.246041,-0.043139,-0.080697,-0.031969,-0.034457,0.001486,-0.021584,-0.018189,-0.042991,-0.027543,-0.036457,0.014456,0.057068,0.164114
C8,0.004194,0.125961,0.119564,0.004197,0.119237,-0.007672,-0.295987,0.020281,-0.098485,-0.201160,-0.009156,-0.062604,1.000000,-0.015194,0.002989,-0.035196,-0.016406,-0.033142,0.003809,-0.020325,-0.007631,-0.032423,-0.004567,-0.011049,0.011445,-0.043861,-0.018584
N1,0.041259,0.017362,0.012089,0.041267,0.014503,-0.051824,0.009429,-0.002296,0.006588,0.264212,-0.037446,-0.246041,-0.015194,1.000000,0.278765,0.423092,0.083125,0.110351,-0.000232,0.052563,0.028004,0.125647,0.053844,0.066858,-0.025641,-0.036554,-0.247088
C9,0.029978,0.112332,0.082722,0.029986,0.083878,0.007018,-0.049385,-0.072116,-0.025080,0.117501,-0.236198,-0.043139,0.002989,0.278765,1.000000,0.305348,-0.018716,0.063283,-0.006667,0.041720,0.018534,0.031879,0.024056,0.028030,-0.015461,0.042772,-0.007290
N2,0.008043,-0.018011,-0.021907,0.008046,-0.020094,-0.024245,0.038045,-0.034679,-0.019544,0.149258,-0.046455,-0.080697,-0.035196,0.423092,0.305348,1.000000,-0.022953,0.039056,-0.003818,0.010070,0.003433,0.010651,0.006042,0.006845,-0.019434,-0.006388,-0.126409
N3,0.117648,0.035546,0.036165,0.117632,0.036497,-0.015229,-0.024341,-0.002251,-0.039773,-0.060791,0.085084,-0.031969,-0.016406,0.083125,-0.018716,-0.022953,1.000000,0.349852,0.127400,0.294465,0.178854,0.681235,0.161171,0.210921,0.019337,-0.013664,-0.075570
N4,0.203383,0.026743,0.026420,0.203410,0.027168,-0.013335,0.012293,-0.002444,-0.010637,0.040794,0.018428,-0.034457,-0.033142,0.110351,0.063283,0.039056,0.349852,1.000000,-0.001632,0.566682,0.304263,0.825176,0.329649,0.368547,-0.004138,0.002419,-0.062559
N5,0.071254,0.006860,0.006853,0.071303,0.006560,-0.005202,-0.003979,0.008495,-0.005169,-0.020289,0.020634,0.001486,0.003809,-0.000232,-0.006667,-0.003818,0.127400,-0.001632,1.000000,-0.000741,-0.000415,0.102013,0.017159,0.031995,0.004289,0.000645,-0.011926
N6,0.230524,0.012628,0.014143,0.230528,0.014412,0.010162,0.021354,0.002335,0.003998,0.024300,0.019519,-0.021584,-0.020325,0.052563,0.041720,0.010070,0.294465,0.566682,-0.000741,1.000000,0.492257,0.669907,0.373009,0.413678,-0.003069,0.001590,-0.028837
N7,0.092622,-0.001135,-0.000400,0.092630,-0.000202,0.005695,0.005619,-0.003647,-0.006557,0.005445,-0.000492,-0.018189,-0.007631,0.028004,0.018534,0.003433,0.178854,0.304263,-0.000415,0.492257,1.000000,0.329226,0.070884,0.108547,-0.000391,0.002268,-0.013838
N8,0.232069,0.035148,0.036550,0.232101,0.037086,-0.013904,0.004571,0.002815,-0.018941,0.007496,0.069547,-0.042991,-0.032423,0.125647,0.031879,0.010651,0.681235,0.825176,0.102013,0.669907,0.329226,1.000000,0.437009,0.493050,0.006068,-0.003296,-0.077851
N9,0.514412,0.013390,0.013527,0.514525,0.013552,-0.006939,0.007887,0.003306,-0.008732,0.015806,0.024832,-0.027543,-0.004567,0.053844,0.024056,0.006042,0.161171,0.329649,0.017159,0.373009,0.070884,0.437009,1.000000,0.904951,-0.010150,-0.005500,-0.024018
N10,0.470503,0.012329,0.012626,0.470614,0.012575,-0.011425,0.010729,0.004317,-0.006200,0.018107,0.029970,-0.036457,-0.011049,0.066858,0.028030,0.006845,0.210921,0.368547,0.031995,0.413678,0.108547,0.493050,0.904951,1.000000,-0.011529,-0.003759,-0.029505
C10,-0.005066,-0.000430,-0.000176,-0.005069,-0.000184,0.000293,-0.055098,0.000864,-0.022361,-0.093148,0.016071,0.014456,0.011445,-0.025641,-0.015461,-0.019434,0.019337,-0.004138,0.004289,-0.003069,-0.000391,0.006068,-0.010150,-0.011529,1.000000,-0.007489,-0.016011
C11,-0.001280,0.053341,0.051994,-0.001278,0.052295,0.072482,0.111602,0.021532,0.128080,0.109476,-0.008306,0.057068,-0.043861,-0.036554,0.042772,-0.006388,-0.013664,0.002419,0.000645,0.001590,0.002268,-0.003296,-0.005500,-0.003759,-0.007489,1.000000,0.380233
C12,-0.016744,0.070517,0.072373,-0.016742,0.071955,0.148559,0.133126,0.074496,0.211202,0.265741,0.039842,0.164114,-0.018584,-0.247088,-0.007290,-0.126409,-0.075570,-0.062559,-0.011926,-0.028837,-0.013838,-0.077851,-0.024018,-0.029505,-0.016011,0.380233,1.000000

We discard the column PurchaseTime because it has an extremely high correlation with the dependant variable (label) that we are trying to predict, additionally we will also discard the column ID because we cannot make a prediction based on a user ID.

In [7]:
df2 = df.drop(['id', 'purchaseTime'], axis=1)
df2.head()

,label,visitTime,hour,C1,C2,C3,C4,C5,C6,C7,C8,N1,C9,N2,N3,N4,N5,N6,N7,N8,N9,N10,C10,C11,C12
0,-1,19274330,0,2569487005,1830830742,4228834423,652481754,2967512603,3624739744,2303407174,2206061889,0,4287642944,0,0,0,0,0,0,0,0,0,419316267,3617851689,4220791646
1,-1,19274334,0,3191875643,403381353,1238330876,652481754,2967512603,179712055,2303407174,157533148,1,3272771221,0,1,0,0,0,0,1,0,0,1968545380,3831440054,1213938795
2,-1,19274353,0,2634604934,403381353,1928325921,652481754,2967512603,1607619193,2303407174,3588031319,0,3329757940,0,0,0,0,0,0,0,0,0,1405802835,2379633508,1284343215
3,-1,19274358,0,2569487005,403381353,296915027,652481754,2967512603,10212495,2303407174,3588031319,0,3427046189,0,0,0,0,0,0,0,0,0,2299319102,3617851689,4220791646
4,-1,19274367,0,2569487005,403381353,681762206,652481754,2967512603,580883881,2303407174,157533148,0,2088887026,0,0,0,0,0,0,0,0,0,1306075469,3617851689,4220791646

In [8]:
# We start by assigning to X all the columns asides from the dependant variable, and to Y only the "label" column
X = df2.loc[:, df2.columns != "label"]
X.head()
Y = df2["label"]
Y.value_counts()

-1    31371
 1    57
Name: label, dtype: int64

We notice that we are dealing with an extremely imbalanced data set

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size = 0.25, random_state = 322, stratify = Y)
print(len(Y_train))
print(Y_train.value_counts())

23571
-1    23528
 1    43
Name: label, dtype: int64

In [10]:
from imblearn.over_sampling import SMOTE

C:\Users\RWM\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:144: FutureWarning: The sklearn.neighbors.base module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.neighbors. Anything that cannot be imported from sklearn.neighbors is now part of the private API.
  warnings.warn(message, FutureWarning)
C:\Users\RWM\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:144: FutureWarning: The sklearn.ensemble.bagging module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.ensemble. Anything that cannot be imported from sklearn.ensemble is now part of the private API.
  warnings.warn(message, FutureWarning)
C:\Users\RWM\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:144: FutureWarning: The sklearn.ensemble.base module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.ensemble. Anything that cannot be imported from sklearn.ensemble is now part of the private API.
  warnings.warn(message, FutureWarning)
C:\Users\RWM\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:144: FutureWarning: The sklearn.ensemble.forest module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.ensemble. Anything that cannot be imported from sklearn.ensemble is now part of the private API.
  warnings.warn(message, FutureWarning)
Using TensorFlow backend.
C:\Users\RWM\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:144: FutureWarning: The sklearn.utils.testing module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.utils. Anything that cannot be imported from sklearn.utils is now part of the private API.
  warnings.warn(message, FutureWarning)
C:\Users\RWM\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:144: FutureWarning: The sklearn.metrics.classification module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.metrics. Anything that cannot be imported from sklearn.metrics is now part of the private API.
  warnings.warn(message, FutureWarning)

In [11]:
# We use SMOTE in order to fix the imbalanced dataset problem
smote = SMOTE(sampling_strategy = 'minority', random_state = 322)
X_train, Y_train= smote.fit_resample(X_train, Y_train)

C:\Users\RWM\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)

In [12]:
# Balancing the dataset
print(len(Y_train))
print("There are {} values equals to 1".format(np.count_nonzero(Y_train == 1)))
print("There are {} values equals to -1".format(np.count_nonzero(Y_train == -1)))

47056
There are 23528 values equals to 1
There are 23528 values equals to -1

# MODELLING USING RANDOMFORESTCLASSIFIER

In [13]:
from sklearn.ensemble import RandomForestClassifier
randomfc = RandomForestClassifier(random_state=322, n_estimators=80)

randomfc.fit(X_train, Y_train)
pred_randomfc = randomfc.predict_proba(X_test)
Y_pred_randomfc = randomfc.predict(X_test)

In [14]:
# Printing the Confusion Matrix
from sklearn.metrics import confusion_matrix
print(confusion_matrix(Y_test, Y_pred_randomfc))

[[7839    4]
 [   7    7]]

In [15]:
from sklearn.model_selection import cross_val_score
from numpy import mean
scores = cross_val_score(randomfc, X, Y, scoring='roc_auc')
print('Mean ROC AUC: %.3f' % mean(scores))

Mean ROC AUC: 0.917

# MODELLING USING LOGISTIC REGRESSION

In [16]:
from sklearn.linear_model import LogisticRegression
logres = LogisticRegression()
logres.fit(X_train,Y_train)
Y_pred = logres.predict(X_test)

print(logres.score(X_train, Y_train))
print(logres.score(X_test, Y_test))

0.7986229173750425
0.8025964108438335

In [17]:
# Printing the Confusion Matrix
from sklearn.metrics import confusion_matrix
print(confusion_matrix(Y_test, Y_pred))

[[6301 1542]
 [   9    5]]

In [18]:
from sklearn.model_selection import cross_val_score
from numpy import mean
scores = cross_val_score(logres, X, Y, scoring='roc_auc')
print('Mean ROC AUC: %.3f' % mean(scores))

Mean ROC AUC: 0.764

When we compare the two models, we noticed that the prediction accuracy of the Random Forest Classifier is much higher than that of the Logistic Regression. Consequently, we will be using Random Forest on the testing set in order to predict the probability of purchase.

# ON THE TESTING SET

In [19]:
test1 = pd.read_csv("test1.csv")
test1.head()
ID = test1["id"]

Due to this being the testing set, we will delete the "label" column as we are not supposed to know the end result

In [20]:
del test1["label"]

Once again, we drop the columns "id" and "purchaseTime" for the same reasons as in the training set.

In [21]:
test1 = test1.drop(['id', 'purchaseTime'], axis=1)

In [22]:
test1.head()

,visitTime,hour,C1,C2,C3,C4,C5,C6,C7,C8,N1,C9,N2,N3,N4,N5,N6,N7,N8,N9,N10,C10,C11,C12
0,19360733,0,2569487005,403381353,681762206,652481754,2967512603,580883881,2303407174,157533148,0,2088887026,0,0,0,0,0,0,0,0,0,2128770044,3617851689,4220791646
1,19360734,0,2416811818,1235983246,3653557526,652481754,2116767313,571765677,2303407174,2374954832,0,2226682598,0,0,0,0,0,0,0,0,0,4256459078,2379633508,1284343215
2,19360735,0,3765056181,1235983246,1310333812,652481754,2116767313,571765677,2303407174,2374954832,0,2226682598,0,0,0,0,0,0,0,0,0,2840358457,3831440054,1213938795
3,19360737,0,955802445,403381353,2290282995,652481754,2967512603,1607619193,1342367140,3588031319,4,3329757940,0,0,0,0,0,0,0,0,0,4039873369,535829057,3828748840
4,19360752,0,2569487005,2517724481,2463986301,2308170622,2967512603,580883881,2303407174,157533148,0,2088887026,0,0,0,0,0,0,0,0,0,907610626,3617851689,4220791646

In [23]:
test_predictions = pd.DataFrame(randomfc.predict_proba(test1))

In [24]:
test1['Prob_0'] = test_predictions[0]
test1['Prob_1'] = test_predictions[1]
test1['ID'] = ID

In [25]:
Final_score = pd.DataFrame()
Final_score['ID'] = test1['ID']
Final_score['Prob_0'] = test1['Prob_0']
Final_score['Prob_1'] = test1['Prob_1']
Final_score.head()

   ID  Prob_0  Prob_1
0  1   0.9625  0.0375
1  2   0.9625  0.0375
2  3   0.9750  0.0250
3  4   0.9750  0.0250
4  5   0.9500  0.0500

In [26]:
Final_score.to_csv("Assignment_2_3_EdwardGreen.csv", index=False)

PermissionError: [Errno 13] Permission denied: 'Assignment_2_3_EdwardGreen.csv'